export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;

export const rolesWithAccess = {
  tambah: ['admin', 'superadmin'],
  tambahakun: ['admin', 'superadmin'],
  edit: ['admin', 'superadmin'],
  delete: ['admin', 'superadmin'],
  kelembagaan: ['admin', 'superadmin'],
  kewilayahan: ['admin', 'superadmin'],
  akademik: ['admin', 'superadmin'],
  pindah: ['admin', 'superadmin'],
  keluar: ['admin', 'superadmin'],
  approve: ['biktren', 'kamtib', 'pengasuh'],
  golongan: ["admin", "superadmin"],
  kewaliasuhan: ["admin", "superadmin"],
  manage: ["admin", "superadmin"],
  kepegawaian: ["admin", "superadmin"],
  santri: ["admin", "superadmin"],
  kitab: ["admin", "superadmin"],
  karturfid: ["admin", "superadmin"],
  dashboard: ["admin", "superadmin"],
  perizinan: ["admin", "superadmin"],
  pelanggaran: ["admin", "superadmin"],
  kunjungan: ["admin", "superadmin"],
  sholat: ["admin", "superadmin"],
  jadwal_sholat: ["admin", "superadmin"],
  khadam: ["admin", "superadmin"],
  presensi_sholat: ["admin", "superadmin", "ustadz"],
  tahfidz: ["admin", "superadmin", "ustadz"],
  nadhoman: ["admin", "superadmin", "ustadz"]
};
